backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "solutions"
    label: "Solutions"
    folder: "src/pages/solutions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "solutions-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "services"
    label: "Services"
    folder: "src/pages/services"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "services",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "text" }
      - { label: "Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "industries"
    label: "Industries"
    folder: "src/pages/industries"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "industries",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "text" }
      - { label: "Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "case-study"
    label: "Case Study"
    folder: "src/pages/case-study"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "case-study",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Home,
              name: home,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Sub Title, name: subTitle, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: About,
              name: about,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Sub Title, name: subTitle, widget: string },
                  { label: Button Text, name: button, widget: string },
                ],
            }
          - {
              label: Location,
              name: location,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Sub Title, name: subTitle, widget: string },
                  { label: Phone, name: phone, widget: string },
                  { label: Email, name: email, widget: string },
                  { label: Address, name: address, widget: text },
                ],
            }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - {
              label: Section,
              name: section,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
