backend:
  name: git-gateway
 # repo: https://github.com/sten-dev/incede-dev-test
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "resources-case-studies"
    label: "Resources Case Studies"
    folder: "src/pages/resources/"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "resources-case-studies",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Solution Type", name: "technology", widget: "select", "multiple":true , "options":[{label: "watsonx.orchestrate", "value": "watsonx.orchestrate", widget: string},{label: "watsonx", "value": "watsonx", widget: string},{label: "Watson Discovery", "value": "watson-discovery", widget: string},{label: "IBM Cognos Analytics", "value": "ibmCcgnos-analytics", widget: string},{label: "Planning Analytics", "value": "planning-analytics", widget: string}]}
      - { label: "Industry", name: "industry", widget: "select", "multiple":true , "options":[{label: "Transportation", "value": "transportation", widget: string},{label: "Insurance", "value": "insurance", widget: string},{label: "Manufacturing", "value": "manufacturing", widget: string},{label: "Services", "value": "services", widget: string},{label: "Finance", "value": "finance", widget: string},{label: "Public Administration", "value": "public-administration", widget: string},{label: "Media", "value": "media", widget: string},{label: "Food and Beverages", "value": "food-and-beverages", widget: string}]}
      - { label: "Sub Title", name: "subTitle", widget: "text" }
      - { label: "Image", name: "image", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
